apiVersion: v1
kind: Namespace
metadata:
  name: reactapp
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
spec:
  finalizers:
  - kubernetes