apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-admin-role
  namespace: reactapp
rules:
- apiGroups:
  - "*"
  resources:
  - "*"
  verbs:
  - Get
  - List
  - Watch
  - Patch