apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-admin-role-app-con
  namespace: reactapp
roleRef:
  apiGroup: rbac.authorization.k8s.io  
  kind: Role
  name: argocd-admin-role
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller 
  namespace: openshift-gitops