apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    "helm.sh/hook": post-install,post-upgrade
  labels:
    app: {{ template "reactapp.name" . }}
  name: {{ template "reactapp.name" .}}
spec:
  host: {{ .Values.route.customHost }}
  port:
    targetPort: {{ .Values.route.targetPort }}
  to:
    kind: Service
    name: {{ template "reactapp.fullname" . }}
    weight: 100
  wildcardPolicy: None